### ISSUE TITLE
azuracast_installer.log

### ISSUE THREAD

**Issue by gunsar** [scysys/AzuraCast-Ubuntu#1]
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
misc/prepare_system.sh: line 13: add-apt-repository: command not found

**Comment by isAAAc** [comment]
hey @gunsar , 
do you still encounter your issue ? 
i just finish the install with some (solved) issues, perhaps because the ubuntu wasn't a fresh clean install
https://github.com/scysys/AzuraCast-Ubuntu/issues?q=is%3Aissue

**Comment by scysys** [comment]
@gunsar 

> misc/prepare_system.sh: line 13: add-apt-repository: command not found

Thats strange. add-apt-repository should be installed by default on Ubuntu 22.04. Make sure you are using the installer only with a fresh installation of Ubuntu 22.04

To fix do this bevor you start the installer

`apt-get install software-properties-common`

**Comment by scysys** [comment]
I just checked on my side. 'software-properties-common' is also inside the installer, so what I wrote before will not help.

I'll do tests before I publish a new release.
Please try again with version 0.0.4 and make sure it is Ubuntu 22.04.

**Installation**

`mkdir /root/azuracast_installer && cd /root/azuracast_installer && git clone https://github.com/scysys/AzuraCast-Ubuntu.git . && git checkout ed05865b5a9b871a72dfd8c17c1002788de49b9c && chmod +x install.sh && ./install.sh -i`

I hope i dont must say it. But make sure you do this command as root user.

**Comment by scysys** [comment]
Which hosting provider do you use, please? I just want to check it myself with the images there.

**Comment by scysys** [comment]
`mkdir /root/azuracast_installer && cd /root/azuracast_installer && git clone https://github.com/scysys/AzuraCast-Ubuntu.git . && chmod +x install.sh && ./install.sh -i`

Do again with main please. I checked main now with hetzner and ovh without problems. Also i updated something in main that can cause your posted error.

**Comment by scysys** [comment]
I dont have access to racknerd or virmach :( The System is the same. I think it should be a problem with the apt sources.list. Maybe i can solve it when i ship the installer with an own sources.list. But it can cause other problems. When i test here for me i only use hetzner and ovh.

**Comment by scysys** [comment]
digitalocean is also ok. ill tested with 2 droplets now.

**Comment by scysys** [comment]
you tried at racknerd again with the new installer version? maybe error message will an other one

**Comment by scysys** [comment]
> OS steps start from Install Ubuntu 20.04, then apt update, apt upgrade, do-release-upgrade -d.

There are no direct ISOs for 22.04? By the way, after a release upgrade, always do a reboot.

> Generate ACME from the azuracast web browser also runs normally for SSL.

Anything inside AzuraCast should run. I tested all functions and have no problems found.

> for RackNerd still a problem

I think i have it

`chown: invalid group: â€˜root:admâ€™`

I also found errors related to this on search engines.
I'll update the main branch to help address this issue from RackNerd's images.

Just do again to test please

`mkdir /root/azuracast_installer && cd /root/azuracast_installer && git clone https://github.com/scysys/AzuraCast-Ubuntu.git . && chmod +x install.sh && ./install.sh -i`

---

You should also write them and ask them why there images missing the default group root:adm group. This group is normally installed by ubuntu itself on first setup.

Anyway you they can test it with theire fresh images with this

`apt-get install nginx`

It will fail because of this missing group.
Maybe there are other things missing on the ISOs. Hopefully not :)

**Comment by scysys** [comment]
Sure just edit the panel conf

`/etc/nginx/sites-available/azuracast.conf`

**HTTP:** https://github.com/scysys/AzuraCast-Ubuntu/blob/main/web/nginx/azuracast.conf#L48
**HTTPS:** https://github.com/scysys/AzuraCast-Ubuntu/blob/main/web/nginx/azuracast.conf#L49

After changed the Port just restart Nginx with

`supervisorctl restart nginx`

**Comment by scysys** [comment]
> SSL reading on icecast kh15 is a bit slow when playing URL. hopefully there is another way to upgrade the icecast to the kh17 or latest version, because it reads ssl faster when playing https url

I also need it and i will those things add later to the installer. For now i must change internally in my side some things. Then i will updates and some other needed stuff.

**Comment by scysys** [comment]
yes it can be all together in one routine or separated into multiple commands

**Comment by scysys** [comment]
Racknerd i have fixed only in main.

`mkdir /root/azuracast_installer && cd /root/azuracast_installer && git clone https://github.com/scysys/AzuraCast-Ubuntu.git . && chmod +x install.sh && ./install.sh -i`

When its occured with your image and puttys fatal error. It is because of your connection.

**Comment by scysys** [comment]
`npm ERR! request to https://registry.npmjs.org/zxcvbn/-/zxcvbn-4.4.2.tgz failed, reason: connect EHOSTUNREACH 2606:4700::6810:1823:443`

Thats connection related by your host there. Can be a misconfiguration of ipv6.

You can check your IPv6 connection to this host with

`ping -6 registry.npmjs.org`

This is not a installer error. If command ping above is ok. Just install again. Could be a temporary error with the other host. I can add checks if this happen to often.

> well, I installed it using the main version

Ill updated that main and listed installer version are the same now.

---

I was curious and tried racknerd myself. No problems after the fix above.

<img width="618" alt="Bildschirm­foto 2023-02-27 um 17 02 15" src="https://user-images.githubusercontent.com/1695531/221615046-cead91a6-8008-49d7-ab47-8db3162aa8b3.png">

**Comment by scysys** [comment]
`It looks like you have to add a note in the readme, the Server besides having to be OS Ubuntu 22 must also be active IP6`

No. It does no matter if you have v4, v6 or both. The error above is not on my or installer side. It is something that should people handle theireself on the host. People who cant do this should always using the docker variant.

**Comment by scysys** [comment]
This here is nothing other here than in the ansible version. Just the install process is different.
You can do custom nginx conf per station here: /var/azuracast/stations/*/config/nginx.conf or also here /etc/nginx/azuracast.conf.d/. unsure if the first one will be overwrited by azura.

But i never have changed those urls. Maybe its not that easy to just change the nginx conf. Maybe the links inside azura will fail then if there is no redirect to new location.

For the Ports i showed you where to change.

HTTP: https://github.com/scysys/AzuraCast-Ubuntu/blob/main/web/nginx/azuracast.conf#L48
HTTPS: https://github.com/scysys/AzuraCast-Ubuntu/blob/main/web/nginx/azuracast.conf#L49

**Comment by scysys** [comment]
Thoose paths are here: /var/azuracast/stations/station_1/config/nginx.conf
But this file is regenerated by azuracast, when you restart your broadcasting.

It seems much more complicated. Also i see a few proxy pass redirections. Thoose things are always bad.
With an high amount of listeners it will always need much more ressource than you normally really need.
In my opinion this is one thing that should be changed inside azura. But i only need it for 5 Listeners on each station. So the proxy redirects are ok for me.

To archive what you want try this

`nano /etc/nginx/azuracast.conf.d/example.conf`

Insert

```
location /stream {
    include proxy_params;

    proxy_intercept_errors    on;
    proxy_next_upstream       error timeout invalid_header;
    proxy_redirect            off;
    proxy_connect_timeout     60;

    proxy_set_header Host example.com;
    proxy_pass https://example.com:port/mountname;
}
```

Before you insert it you must change

example.com = your domain
port = port of your station
mountname = with the stations moutname

So if you have 

https://example.com:8160/stream

It must be

```
proxy_set_header Host example.com;
proxy_pass https://example.com:8160/stream;
```

So

https://example.com:8160/stream

Will become

https://example.com/stream

Not tested. But should work.

At the End you do this command to restart anything

`supervisorctl restart all`

BTW: For Ports and Icecast Update ill added options to the installer :p

**Comment by scysys** [comment]
Should be just a connection error. nothing i can do in thoose cases. Just try reinstall

> fetch-pack: unexpected disconnect while reading sideband packet

**Comment by scysys** [comment]
you can start a screen to prevent abort of connections issues. just enter

`screen`

and then start the installer.

if you loose connection, just connection again and do

`screen -r`

to access your latest session.

----

If you want please test also the new liquidsoap commands on your side :)

**Comment by scysys** [comment]
> but the settings in icecast.xml for each station are still not working until now.

Dont understand. Error in Installer? Or AzuraCast related?

**Comment by scysys** [comment]
What is the advantage of using multiple ports for one station? I don't see why it makes sense :)

**Comment by scysys** [comment]
Ah i understand. The settings under Custom Frontend Configuration will be placed under the mountpoint. So thats what the devs wanted. But for listen-socket its just the wrong location. I personally dont think it makes sense to add a new configuration field for those things. You can also just add a second mountpoint to open another port and relay the other one.

**Comment by scysys** [comment]
no no there is install missing in this case. thats just a ulimits part

**Comment by scysys** [comment]
It's not necessary to update the code for such things here.

As soon as it's officially released, you can upgrade Liquidsoap with the following command:

    -n, --liquidsoaplatest: Install / Update to the latest released Liquidsoap version

However, version 2.1.5 is a pre-release. You must wait for the Savonet team to officially publish it here: https://github.com/savonet/liquidsoap-release-assets/releases

Once you see version 2.1.5 there, you can upgrade Liquidsoap.

**Comment by scysys** [comment]
```
supervisorctl stop all
arch=$(dpkg --print-architecture | awk -F- '{ print $NF }')
release_url="https://github.com/savonet/liquidsoap/releases/download/rolling-release-v2.1.x/liquidsoap-fb688f6_2.1.5-ubuntu-jammy-1_$arch.deb"
curl -LO "$release_url"
dpkg -i liquidsoap-fb688f6_2.1.5-ubuntu-jammy-1_$arch.deb
apt-get update
apt-get upgrade -y
rm liquidsoap-fb688f6_2.1.5-ubuntu-jammy-1_$arch.deb
supervisorctl start all
```

Do one by one and when possible to an backup. Not tried :p
