### ISSUE TITLE
Great Work thank you :)

### ISSUE THREAD

**Issue by meintobi** [scysys/AzuraCast-Ubuntu#11]
I have tested and the installer is wunderfull. The Docker Install doesnt worked, but this is option is working.
But after the Install, i become on the Site to configure Azuracast a 500 Error. That's bad ;)

**Comment by scysys** [comment]
I have tested and the installer is wunderfull. The Docker Install doesnt worked, but this is option is working.

Nice to hear

> But after the Install, i become on the Site to configure Azuracast a 500 Error. That's bad ;)

Error 500 with this Installer here? Than i think you have not rebooted. I was lazy. Therefore a reboot is needed after the installation. This made it easier for me to just not notice a few things :p

**Comment by meintobi** [comment]
No sorry, i not lazy and have read all ;))) So i restart, but the Site is a 500 Error, to finish the Install i don't know whats wrong. The Installer works wunderfull.

**Comment by scysys** [comment]
Haha i meaned me not you :) Have you really reboot the server?

If you really have go on console and try to type

`supervisorctl restart all`

**Comment by meintobi** [comment]
I understand you =) it was a joke :) because much peoples don't read all or fully.

Thanks for ur support, i think i have reboot it, but i don't tested further. I only write this comment for my experience. Maybe it is not a error, but it was my Result for the Test.
Now i use the Docker installation with a trick ;)

Thanks for your work and all the best for you.

**Comment by scysys** [comment]
Great! Error 500 will only displayed when you check the install directly when it was finished without a reboot. Maybe i should implant a reboot in installer. So user cant miss it :)
