### ISSUE TITLE
Meilisearch is missing?

### ISSUE THREAD

**Issue by NicoxDJ** [scysys/AzuraCast-Ubuntu#12]
Hey! Is there any option, to add the installation and supervisor config for Meilisearch?
It's been driving me crazy this red error, and i don't think so that AzuraCast will fix their Ansible installer...

**Comment by scysys** [comment]
What Red error? If you install it from here there is no Meilisearch. This is actually 0.17.6.

<img width="1135" alt="Bildschirm­foto 2023-04-02 um 18 59 39" src="https://user-images.githubusercontent.com/1695531/229367555-439d4816-c7f9-4d0b-97f5-b6baa8c67787.png">

As soon i will allow to upgrade to newer versions here, i will for sure add the new meilisearch integration.

**Comment by NicoxDJ** [comment]
@scysys, I updated from the original AzuraCast installer to 0.17.7. Everything was bad, i bought the Rolling Release will fix the problems but not, now i had even more problems. But with your repo, i made it a little bit stable. Just need the installer for Meilisearch, to fix this service.
![](https://i.imgur.com/rVhhmUT.png)

**Comment by scysys** [comment]
Im sorry for this. You need to wait. I think its not optimal too fix your existing Installation with this repro here. Maybe you will run in other problems.
