### ISSUE TITLE
latest-rolling-release

### ISSUE THREAD

**Issue by dougllasvieira** [scysys/AzuraCast-Ubuntu#18]
Hi.
https://github.com/scysys/AzuraCast-Ubuntu#installation-latest-rolling-release
not working

`root@stream03:~# mkdir /root/azuracast_installer && cd /root/azuracast_installer && git clone https://github.com/scysys/AzuraCast-Ubuntu.git . && git checkout rolling && chmod +x install.sh && ./install.sh --install_rrc
Cloning into '.'...
remote: Enumerating objects: 1021, done.
remote: Counting objects: 100% (457/457), done.
remote: Compressing objects: 100% (246/246), done.
remote: Total 1021 (delta 240), reused 409 (delta 204), pack-reused 564
Receiving objects: 100% (1021/1021), 171.64 KiB | 15.60 MiB/s, done.
Resolving deltas: 100% (530/530), done.
error: pathspec 'rolling' did not match any file(s) known to git
`

**Comment by scysys** [comment]
I make mistake in command. Is updated

`mkdir /root/azuracast_installer && cd /root/azuracast_installer && git clone https://github.com/scysys/AzuraCast-Ubuntu.git . && git checkout main && chmod +x install.sh && ./install.sh --install_rrc`
